version: '2'

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}

services:
  flask-test:
    build:
      context: .
      dockerfile: ./compose/local/flask-test/Dockerfile
    depends_on:
      - postgres
    env_file:
      - ./.envs/local/.env
    ports:
      - "5000:5000"
    command: flask run --host=0.0.0.0
    volumes:
      - .:/application

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    env_file:
      - ./.envs/local/.env



