version: '2'

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}

services:
  flask-test:
    build:
      context: .
      dockerfile: ./compose/local/flask-test/Dockerfile
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=portfolio
      - POSTGRES_HOST=postgres
      - POSTGRES_DB_NAME=portfolio
      - FLASK_APP=flask-test/flask-test.py
    ports:
      - "5000:5000"
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    environment:
      - POSTGRES_USER=portfolio
      - POSTGRES_HOST=postgres
      - POSTGRES_DB_NAME=portfolio



