version: '2'

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}

  flasktest:
    build:
      context: .
      dockerfile: ./compose/local/flasktest/Dockerfile
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=portfolio
      - POSTGRES_HOST=postgres
      - POSTGRES_DB_NAME=portfolio
      - USE_DOCKER=yes
    ports:
      - "8000:8000"
    command: /start.sh

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    environment:
      - POSTGRES_USER=portfolio
      - POSTGRES_HOST=postgres
      - POSTGRES_DB_NAME=portfolio