version: '2'

volumes:
  postgres_data_production: {}
  postgres_backup_production: {}

services:
  flasktest:
    build:
      context: .
      dockerfile: ./compose/production/flask-test/Dockerfile
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    command: /gunicorn.sh
    env_file:
      - ./.envs/production/.env

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    volumes:
      - postgres_data_production:/var/lib/postgresql/data
      - postgres_backup_production:/backups
    env_file:
      - ./.envs/production/.env

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      - flasktest
